### ISSUE TITLE
spotify will not install on justboom playr

### ISSUE THREAD

**Issue by shawaj** [PiSupply/JustBoom#13]
[spop.zip](https://github.com/PiSupply/JustBoom/files/2018510/spop.zip)
Use spop.zip and manually upload for now, pending a fix

**Comment by shawaj** [comment]
See https://github.com/volumio/volumio-plugins/issues/89

**Comment by ChristopherRush** [comment]
I believe we can close this now since Spotify is an approved plugin and installed by default.
