### ISSUE TITLE
Upload Logo

### ISSUE THREAD

**Issue by francesco-vannini** [PiSupply/JustBoom#8]
![justboom2](https://user-images.githubusercontent.com/16068311/30544970-24597e94-9c80-11e7-93d3-29cde33c66c0.png)

**Comment by francesco-vannini** [comment]
Use this thread to add pictures

**Comment by ChristopherRush** [comment]
![justboom-github-banner](https://user-images.githubusercontent.com/1878314/73881011-7e819e80-4857-11ea-886f-25fa23f721ce.png)
